//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int InvoiceID { get; set; }
        public double TotalPrice { get; set; }
        public string TypeOfPayment { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string IsPaid { get; set; }
    
        public virtual customerOrder customerOrder { get; set; }
    }
}
